### PR TITLE
[Server] Data storage will updated without clients

### PR DESCRIPTION
**Pull request by thegrymek**
Hi,

I made some changes due to not working properly `ctrl+c` when no web clients are connected.

Changes:
- added storage module for keep data
- moved function `update_game_state` to task where are server running.
  By this, we receive updates even any client are connected. Ctrl+C is easier to do
- moved function `dump_state` and `dump_settings` as standalone functions

### CODE REVIEW

**Comment by sides** [comment]
Hi, thanks for the PR. I have a few comments:

This seems like an awful lot of code to fix what is essentially only a minor dev issue.

I had started a similar change in 622f4b14e748c9564b0eff65438f6fb8ce617bc7 (`single-instance-state` branch). Though this came from concern of the inherently bad design of running a loop for each client (with side-effects such as ctrl+c not working). I ended up not doing this because in the current state the tool worked well with multiple casters having used it on stream with success. So, I just wanted to leave it as-is.

I've since developed my own personal streaming tool which works similarly to this project and is based on it. It has certainly been tested enough to work, so if I want to improve the stability/code of this project I will most likely merge changes from that. (Making ctrl+c work.)

Furthermore, Reforged will most likely have a beta release in November. If the beta will roll out with native observer tools, this project will be immediately obsolete.

For the reasons above I'm gonna put this on hold. My question to you is: Is this problem very important to you? Is it something beyond just ctrl+c not working? If your setup direly requires this change to work then I'll look at this.

**Comment by thegrymek** [comment]
Sure, wait for reforged. Last two weeks showed that mr is not important

**Comment by thegrymek** [comment]
Ok, for working observer mode in reforged we will wait much longer I suppose. Can you please, check and review this pull request?

**Comment by sides** [comment]
Well, at the lack of immediate need for this (dev only) and with the high amount of changes, I'm closing this. There are simpler ways to get ctrl+c to behave normally, but either way it involves adding untested backend changes for something trivial.

Addendum: I'm gonna wait for the Reforged release and see if the observer API is still active on the client. If it is, expect some updates to this (including server overhauls).

**Comment by sides** [comment]
Addendum: I'm gonna wait for the Reforged release and see if the observer API is still active on the client. If it is, expect some updates to this (including server overhauls).

**Pull request closed without merging**
